[project]
name = "boring-stuff"
version = "0.1.0"
dependencies = [
    "pyyaml",
    "openpyxl",
    "yt-dlp[build-in-js-interpreter,javascript]>=2026.3.17",
    "quickjs>=1.19.4",
    "googlesearch-python>=1.3.0",
    "pillow>=12.3.0",
    "pyperclip>=1.11.0",
    "pywin32>=312; sys_platform == 'win32'",
    "xmltodict>=1.0.4",
    "audio-extract>=0.7.0",
    "setuptools<80",
]

[project.scripts]
hello = "scripts.hello:main"
clean-logs = "scripts.cleanup:run"
youtube = "scripts.webs.youtube:main"
yt = "scripts.webs.youtube:main"
clipsave = "wins.clipsave:main"
b64d = "devs.base64_clip:main_decode"
b64e = "devs.base64_clip:main_encode"
prune-branches = "devs.prune_branches:main"
lucky = "cases.webs.lucky:main"
mapit = "cases.maps.mapit:main"
negative = "cases.pictures.negative:main"
pinterest = "cases.webs.pinterest:main"
openwebs = "cases.webs.openwebs:main"
mp4to3 = "cases.webs.mp4to3:main"

[tool.setuptools]
packages = []  # Tells it not to look for library packages
py-modules = [] # Tells it not to look for top-level modules

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
